---
dist: trusty
sudo: required

cache:
  directories:
    - "$(npm config get prefix)/bin"

language: python
python: '2.7'

matrix:
  fast_finish: true

env:
  - TEST_RUN="tests/markdownlint-cli-test.sh"
  - TEST_RUN="tests/textlint-test.sh"
  - TEST_RUN="tests/shellcheck-test.sh"
  - TEST_RUN="tests/signed-off-by-test.sh"

install:
  - nvm install stable
  - nvm use stable

script: "$TEST_RUN"

notifications:
  email: false
